Repository IWFSG/FSG-Backend, pull requests merged in 2022-12, with the labels that each got.

#6 :recycle: post컬럼 수정
  src/main/kotlin/com/iwfsg/board/domain/post/entity/Post.kt
Labels: refactoring

#8 🔀 :: 7-엔티티 생성오류 수정
  src/main/kotlin/com/iwfsg/board/domain/comment/entity/Comment.kt
  src/main/kotlin/com/iwfsg/board/domain/like/entity/Like.kt
  src/main/kotlin/com/iwfsg/board/domain/post/entity/Post.kt
  src/main/kotlin/com/iwfsg/board/domain/user/entity/User.kt
  src/main/kotlin/com/iwfsg/board/global/common/entity/BaseIdEntity.kt
  src/main/kotlin/com/iwfsg/board/global/common/entity/BaseIdTimeEntity.kt
  src/main/kotlin/com/iwfsg/board/global/common/entity/BaseTimeEntity.kt
Labels: bug

#14 Feature/13 create error handler
  src/main/kotlin/com/iwfsg/board/global/error/error_code/ErrorCode.kt
  src/main/kotlin/com/iwfsg/board/global/error/exception/BasicException.kt
  src/main/kotlin/com/iwfsg/board/global/error/handler/GlobalExceptionHandler.kt
  src/main/kotlin/com/iwfsg/board/global/error/response/ErrorResponse.kt
Labels: feature

#16 🔀 ::15-리프레쉬 토큰과 조회수 엔티티 구현
  build.gradle.kts
  src/main/kotlin/com/iwfsg/board/domain/post/entity/Views.kt
  src/main/kotlin/com/iwfsg/board/domain/user/entity/RefreshToken.kt
Labels: feature

#18 🔀 :: 17- Redis설정
  build.gradle.kts
  src/main/kotlin/com/iwfsg/board/BoardApplication.kt
  src/main/kotlin/com/iwfsg/board/global/common/.gitKeep
  src/main/kotlin/com/iwfsg/board/global/redis/config/RedisConfig.kt
  src/main/kotlin/com/iwfsg/board/global/redis/properties/RedisProperties.kt
Labels: feature

#20 🔀 :: 19- 카테고리 엔티티 개발
  src/main/kotlin/com/iwfsg/board/domain/post/entity/Category.kt
Labels: feature

#22 🔀 :: 11 -Feature/security setting
  build.gradle.kts
  src/main/kotlin/com/iwfsg/board/BoardApplication.kt
  src/main/kotlin/com/iwfsg/board/domain/user/domain/exception/UserNotFoundException.kt
  src/main/kotlin/com/iwfsg/board/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/iwfsg/board/global/error/error_code/ErrorCode.kt
  src/main/kotlin/com/iwfsg/board/global/jwt/JwtProperties.kt
  src/main/kotlin/com/iwfsg/board/global/jwt/JwtTokenProvider.kt
  src/main/kotlin/com/iwfsg/board/global/security/auth/CustomUserDetails.kt
  src/main/kotlin/com/iwfsg/board/global/security/auth/service/UserDetailsService.kt
  src/main/kotlin/com/iwfsg/board/global/security/exception/ExpiredTokenException.kt
  src/main/kotlin/com/iwfsg/board/global/security/exception/InvalidTokenException.kt
Labels: setting

#24 🔀 :: 23 - RedisConfig 오류
  src/main/kotlin/com/iwfsg/board/global/redis/config/RedisConfig.kt
Labels: bug

#26 🔀 :: 25 - 레디스 엔티티 오류
  src/main/kotlin/com/iwfsg/board/domain/post/entity/Views.kt
  src/main/kotlin/com/iwfsg/board/domain/user/entity/RefreshToken.kt
Labels: bug
